name: Build and upload

on:
  push:
    tags:
      - 'v-test-*'  # Push events matching v*. i.e v1.0, v2.0

jobs:
  build-and-upload:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
          set +e
          docker info
          docker run --rm -v "$(pwd):/src" --workdir /src erlang:21.3 ./build