name: Build and upload

on: [push, pull_request]

jobs:
  build-and-upload:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
          rebar3 compile
