name: Build and upload

on:
  push:
    tags:
      - 'v-test-*'  # Push events matching v*. i.e v1.0, v2.0

jobs:
  build-and-upload:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
          set +e
          docker info
          docker build -t eqmx/elvis:v0.1 .
          docker run -d --name=elvis-rocks eqmx/elvis -v /tmp:/root/elvis
          /tmp/elvis rocks